root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "tmp\\main.exe"
#cmd = "go build -o ./tmp/main.exe ."
cmd = "go build -o ./tmp/main.exe ./cmd/worker/."
delay = 1000 # ms
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "bin",
  "build",
  "deploy",
  "docs",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true # false
follow_symlink = true # false
full_bin = ""
include_dir = [] # ["**"]
include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "yml", "toml", "env"]
include_file = []
kill_delay = 500 # ms #"0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 0
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true       # false

[misc]
clean_on_exit = true # false

[screen]
clear_on_rebuild = false
keep_scroll = true
