version: "3.8"

volumes:
  pg-data:
    driver: local

services:

  db-primary:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=admin # - POSTGRES_PASSWORD=123
      - POSTGRESQL_DATABASE=rinha  # - POSTGRES_USER=admin
      - POSTGRESQL_PASSWORD=123 # - POSTGRES_DB=rinha
      # - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5435:5432' #- "5432:5432" 
    # expose:
    #   - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data # - ./data:/var/lib/postgresql/data
      - ./configs/postgres.conf:/etc/postgresql/postgresql.conf # - pg-config:/etc/postgresql
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"] #entrypoint: [ "docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf"
      ]
      
  db-replica:
    image: postgres:latest
    hostname: dbreplica
    restart: always
    ports:
      - '5433:5432'
    depends_on:
      - db-primary
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_MASTER_HOST=db-primary
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
